"""create drops

Revision ID: 22c3b4b1cee6
Revises: 
Create Date: 2026-09-16 22:18:15.679276

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '22c3b4b1cee6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, please adjust! ###
    op.create_table('drops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('access', sa.Enum('public', 'private', 'one_time', name='accesstype', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'consumed', name='dropstatus', native_enum=False, length=16), nullable=False),
    sa.Column('retention', sa.Enum('1h', '12h', '1d', '3d', name='retention', native_enum=False, length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('owner_token_hash', sa.String(length=64), nullable=False),
    sa.Column('total_size', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drops')),
    sa.UniqueConstraint('code', name=op.f('uq_drops_code'))
    )
    op.create_index(op.f('ix_drops_expires_at'), 'drops', ['expires_at'], unique=False)
    op.create_index('uq_drops_name_lower', 'drops', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('drop_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drop_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.id'], name=op.f('fk_drop_files_drop_id_drops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drop_files'))
    )
    op.create_index(op.f('ix_drop_files_drop_id'), 'drop_files', ['drop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic, please adjust! ###
    op.drop_index(op.f('ix_drop_files_drop_id'), table_name='drop_files')
    op.drop_table('drop_files')
    op.drop_index('uq_drops_name_lower', table_name='drops')
    op.drop_index(op.f('ix_drops_expires_at'), table_name='drops')
    op.drop_table('drops')
    # ### end Alembic commands ###
